# Generated by Django 5.2.1 on 2025-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_anuncio_fotoanuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanante',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('vip', 'VIP')], default='basico', max_length=10),
        ),
    ]
